CREATE ROLE "learningDbUser" WITH
	LOGIN
	SUPERUSER
	CREATEDB
	CREATEROLE
	INHERIT
	REPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'root';

CREATE DATABASE "LearningDb"
    WITH
    OWNER = "learningDbUser"
    ENCODING = 'UTF8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;